version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - typesense
    env_file:
      - .env
    volumes:
      - .:/app
    # Removed the /var/log/myapp volume as we're now logging to stdout

  typesense:
    image: typesense/typesense:0.23.1
    ports:
      - "8108:8108"
    volumes:
      - ./data/typesense-data:/data
    command: ["--data-dir", "/data", "--api-key", "YourTypesenseAPIKey", "--listen-port", "8108"]

  promtail:
    image: grafana/promtail:main
    volumes:
      - ./promtail:/etc/promtail
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/config.yaml
