version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - typesense
      - promtail
    env_file:
      - .env
    volumes:
      - .:/app
      - /var/log/myapp:/var/log/myapp
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]
    environment:
      - LOG_PATH=/var/log/myapp/app.log

  typesense:
    image: typesense/typesense:0.23.1
    ports:
      - "8108:8108"
    volumes:
      - ./data/typesense-data:/data
    command: ["--data-dir", "/data", "--api-key", "YourTypesenseAPIKey", "--listen-port", "8108"]

  promtail:
    image: grafana/promtail:main
    volumes:
      - ./promtail/config.yaml:/etc/promtail/config.yaml
      - /var/log/myapp:/var/log/myapp
    command: -config.file=/etc/promtail/config.yaml
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9080/ready" ]
      interval: 30s
      timeout: 10s
      retries: 3
