server:
  http_listen_port: 0
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: https://954187:glc_eyJvIjoiMTE4MzY2NiIsIm4iOiJsb2tpLWFwaS1rZXktZmlyc3QtdG9rZW4iLCJrIjoiazFtejUxMjZWTHEzOGxUUjh5MDNodlpCIiwibSI6eyJyIjoidXMifX0=@logs-prod-006.grafana.net/loki/api/v1/push

scrape_configs:
- job_name: app_logs
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      service_name: myapp
      __path__: /var/log/myapp/*.log
